# -*- coding: utf-8 -*-
"""spotify_helper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_bTO75Tg02mlLjkwGQ1XkYKhoKFoRimA
"""

import os
import requests
from dotenv import load_dotenv

load_dotenv()  # .env 파일에서 SPOTIFY_CLIENT_ID, CLIENT_SECRET 불러오기

emotion_to_keyword = {
    "우울(부정)": "sad songs",
    "불안(부정)": "relaxing music",
    "행복(긍정)": "feel good pop",
    "분노(부정)": "angry rock",
    "중립": "lofi chill"
}

def get_spotify_token():
    client_id = os.getenv("SPOTIFY_CLIENT_ID")
    client_secret = os.getenv("SPOTIFY_CLIENT_SECRET")

    response = requests.post(
        'https://accounts.spotify.com/api/token',
        data={'grant_type': 'client_credentials'},
        auth=(client_id, client_secret)
    )
    return response.json().get("access_token")

def search_spotify_tracks(keyword, token, limit=10):
    url = f"https://api.spotify.com/v1/search?q={keyword}&type=track&limit={limit}"
    headers = {"Authorization": f"Bearer {token}"}
    res = requests.get(url, headers=headers)
    items = res.json().get("tracks", {}).get("items", [])

    return [{
        "track_name": item["name"],
        "artist": item["artists"][0]["name"],
        "preview_url": item.get("preview_url"),
        "spotify_url": item["external_urls"]["spotify"]
    } for item in items]