# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_bTO75Tg02mlLjkwGQ1XkYKhoKFoRimA
"""

from fastapi import FastAPI
from pydantic import BaseModel
from emotion_analyzer import analyze_long_text
from spotify_helper import emotion_to_keyword, get_spotify_token, search_spotify_tracks

app = FastAPI()

class TextInput(BaseModel):
    text: str

@app.post("/recommend")
def recommend_music(input: TextInput):
    emotion = analyze_long_text(input.text)
    keyword = emotion_to_keyword.get(emotion, "chill")
    token = get_spotify_token()
    tracks = search_spotify_tracks(keyword, token)
    return {"emotion": emotion, "tracks": tracks}